const mockTasks = [
  { id: 1, description: 'Some random task you need to do and describe a lot about it because it is very involved',
    priority: 3, time: '1 hr'},
  { id: 2, description: 'Some other random task you need to do.',
    priority: 3, time: '0.5 hr'},
  { id: 3, description: 'Important task you need to do and describe a lot about it because it is very involved. It even got more involved so you had to add a sentence or two',
    priority: 1, time: '2 hr'},
  { id: 4, description: 'Important task you need to do and describe a lot about it because it is very involved',
    priority: 1, time: '1 hr'},
  { id: 5, description: 'Task you need to do and describe a lot about it because it is very involved',
    priority: 2, time: '1 hr'},
  { id: 6, description: 'Task you need to do',
    priority: 2, time: '1 hr'},
  { id: 7, description: 'Task',
    priority: 2, time: '1 hr'},
  { id: 8, description: 'Long ass task you need to do and describe a lot about it because it is very involved',
    priority: 2, time: '1 week'},
  { id: 9, description: 'Some random task you need to do and describe a lot about it because it is very involved',
    priority: 3, time: '1 hr'},
  { id: 10, description: 'Some random task you need to do and describe a lot about it because it is very involved',
    priority: 3, time: '1 hr'},
];